# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: "espansoÂ²"
    replace: "Kikoo lol !"

  # Signature
  - trigger: "dngÂ²"
    replace: "Bien cordialement,\n\n-- \nGuillaume Delanoy\nguillaume@delanoy.fr"

    # Date
    #  - trigger: "dÂ²"
    # replace: "{{mydate}}"
    # vars:
    #   - name: mydate
    #    type: date
    #    params:
    #      format: "%d/%m/%Y"

  - trigger: "dateÂ²"
    replace: "{{madate}}"
    vars:
      - name: madate
        type: date
        params:
          format: "%A %d %B %Y"

  # Heure
  - trigger: "hmÂ²"
    replace: "Il est {{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%Hh%M"

  # Shell commands
#  - trigger: ":shell"
#    replace: "{{output}}"
#    vars:
#      - name: output
#        type: shell
#        params:
#          cmd: "echo Hello from your shell"

# Remplacer des caractÃ¨res par d'autres :

  - trigger: "szÂ²"
    replace: "ÃŸ"

  - trigger: "cÂ²"
    replace: "Â©"

  - trigger: "crÂ²"
    replace: "Â®"

  - trigger: "1/2"
    replace: "Â½"
    word: true

  - trigger: "1/4"
    replace: "Â¼"
    word: true

  - trigger: "3/4"
    replace: "Â¾"
    word: true

  - trigger: "Ã§Â²"
    replace: "Ã‡"

  - trigger: "Ã©Â²"
    replace: "Ã‰"

  - trigger: "Ã¨Â²"
    replace: "Ãˆ"

  - trigger: "ÃªÂ²"
    replace: "ÃŠ"

  - trigger: "Ã¹Â²"
    replace: "Ã™"

  - trigger: "Ã Â²"
    replace: "Ã€"

  - trigger: "aeÂ²"
    replace: "Ã¦"

  - trigger: "oeÂ²"
    replace: "Å“"

# Remplacements personnalisÃ©s

  - trigger: "rÂ²"
    replace: "rÃ©pondre"
    word: true

  - trigger: "gÂ²"
    replace: "Guillaume"
    word: true

  - trigger: "dÂ²"
    replace: "Delanoy"
    word: true

  - trigger: "gdÂ²"
    replace: "Guillaume Delanoy"
    word: true

  - trigger: "aaÂ²"
    replace: "AurÃ©lie-Anne"
    word: true

  - trigger: "geÂ²"
    replace: "Â¯\_(ãƒ„)_/Â¯"
    word: true

  - trigger: "bjrÂ²"
    replace: "bonjour"

  - trigger: "ajdÂ²"
    replace: "aujourd'hui"

  - trigger: "roflÂ²"
    replace: "ğŸ¤£"

  - trigger: "heyesÂ²"
    replace: "ğŸ˜"

  - trigger: "kissÂ²"
    replace: "ğŸ˜˜"

  - trigger: "maskÂ²"
    replace: "ğŸ˜·"

  - trigger: "wutÂ²"
    replace: "ğŸ˜³"

  - trigger: "sobÂ²"
    replace: "ğŸ˜­"

  - trigger: "poopÂ²"
    replace: "ğŸ’©"

  - trigger: "boomÂ²"
    replace: "ğŸ’¥"

  - trigger: "fuckÂ²"
    replace: "ğŸ–•"

  - trigger: "(y)"
    replace: "ğŸ‘"

  - trigger: "yÂ²"
    replace: "ğŸ‘"

  - trigger: "deÂ²"
    replace: "ğŸ‡©ğŸ‡ª"

  - trigger: "omÂ²"
    replace: "ğŸ•‰"

  - trigger: "frÂ²"
    replace: "ğŸ‡«ğŸ‡·"

  - trigger: "gbÂ²"
    replace: "ğŸ‡¬ğŸ‡§"

# Lutter contre la dyslexie dans les commandes :

  - trigger: "sud o "
    replace: "sudo "

  - trigger: "sduo "
    replace: "sudo "
    word: true
