# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: "espansoÂ²"
    replace: "Kikoo lol !"

  # Signature
  - trigger: "dngÂ²"
    replace: "Bien cordialement,\n\n-- \nGuillaume Delanoy\nguillaume@delanoy.fr"

    # Date
    #  - trigger: "dÂ²"
    # replace: "{{mydate}}"
    # vars:
    #   - name: mydate
    #    type: date
    #    params:
    #      format: "%d/%m/%Y"

  - trigger: "dateÂ²"
    replace: "{{madate}}"
    vars:
      - name: madate
        type: date
        params:
          format: "%A %d %B %Y"

  # Heure
  - trigger: "hmÂ²"
    replace: "Il est {{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%Hh%M"

  # Shell commands
#  - trigger: ":shell"
#    replace: "{{output}}"
#    vars:
#      - name: output
#        type: shell
#        params:
#          cmd: "echo Hello from your shell"

# Remplacer des caractÃ¨res par d'autres :

  - trigger: "szÂ²"
    replace: "ÃŸ"

  - trigger: "cÂ²"
    replace: "Â©"

  - trigger: "crÂ²"
    replace: "Â®"

  - trigger: "1/2"
    replace: "Â½"
    word: true

  - trigger: "1/4"
    replace: "Â¼"
    word: true

  - trigger: "3/4"
    replace: "Â¾"
    word: true

  - trigger: "Ã§Â²"
    replace: "Ã‡"

  - trigger: "Ã©Â²"
    replace: "Ã‰"

  - trigger: "Ã¨Â²"
    replace: "Ãˆ"

  - trigger: "Ã¹Â²"
    replace: "Ã™"

  - trigger: "Ã Â²"
    replace: "Ã€"

  - trigger: "aeÂ²"
    replace: "Ã¦"

  - trigger: "oeÂ²"
    replace: "Å“"

# Remplacements personnalisÃ©s

  - trigger: "rÂ²"
    replace: "rÃ©pondre"
    word: true

  - trigger: "gÂ²"
    replace: "Guillaume"
    word: true

  - trigger: "ggmÂ²"
    replace: "gdelanoy@gmail.com"
    word: true

  - trigger: "gdmÂ²"
    replace: "guillaume@delanoy.fr"
    word: true

  - trigger: "adgmÂ²"
    replace: "16 / 6, square Jean Monnet - 59120 Loos"
    word: true

  - trigger: "dÂ²"
    replace: "Delanoy"
    word: true

  - trigger: "gdÂ²"
    replace: "Guillaume Delanoy"
    word: true

  - trigger: "aaÂ²"
    replace: "AurÃ©lie-Anne"
    word: true

  - trigger: "geÂ²"
    replace: "Â¯\\_(ãƒ„)_/Â¯"
    word: true

  - trigger: "bjrÂ²"
    replace: "bonjour"

  - trigger: "ajdÂ²"
    replace: "aujourd'hui"

  - trigger: "lolÂ²"
    replace: "ğŸ˜„"

  - trigger: "winkÂ²"
    replace: "ğŸ˜‰"

  - trigger: "angelÂ²"
    replace: "ğŸ˜‡"

  - trigger: "thinkÂ²"
    replace: "ğŸ¤”"

  - trigger: "vomitÂ²"
    replace: "ğŸ¤®"

  - trigger: "fearÂ²"
    replace: "ğŸ˜±"

  - trigger: "rageÂ²"
    replace: "ğŸ¤¬"

  - trigger: "clownÂ²"
    replace: "ğŸ¤¡"

  - trigger: "santaÂ²"
    replace: "ğŸ…"

  - trigger: "popcornÂ²"
    replace: "ğŸ¿"

  - trigger: "champÂ²"
    replace: "ğŸ¾"

  - trigger: "beerÂ²"
    replace: "ğŸ»"

  - trigger: "roflÂ²"
    replace: "ğŸ¤£"

  - trigger: "heyesÂ²"
    replace: "ğŸ˜"

  - trigger: "kissÂ²"
    replace: "ğŸ˜˜"

  - trigger: "maskÂ²"
    replace: "ğŸ˜·"

  - trigger: "wutÂ²"
    replace: "ğŸ˜³"

  - trigger: "sobÂ²"
    replace: "ğŸ˜­"

  - trigger: "poopÂ²"
    replace: "ğŸ’©"

  - trigger: "boomÂ²"
    replace: "ğŸ’¥"

  - trigger: "fuckÂ²"
    replace: "ğŸ–•"

  - trigger: "(y)"
    replace: "ğŸ‘"

  - trigger: "yÂ²"
    replace: "ğŸ‘"

  - trigger: "swÂ²"
    replace: "ğŸ˜…"

  - trigger: "bwaÂ²"
    replace: "ğŸ¤ª"

  - trigger: "smirkÂ²"
    replace: "ğŸ˜"

  - trigger: "coldÂ²"
    replace: "ğŸ¥¶"

  - trigger: "cultureÂ²"
    replace: "ğŸ§"

  - trigger: "devilÂ²"
    replace: "ğŸ˜ˆ"

  - trigger: "skullÂ²"
    replace: "â˜ "

  - trigger: "alienÂ²"
    replace: "ğŸ‘½"

  - trigger: "heartÂ²"
    replace: "ğŸ’–"

  - trigger: "roseÂ²"
    replace: "ğŸŒ¹"

  - trigger: "worldÂ²"
    replace: "ğŸŒ"

  - trigger: "gyroÂ²"
    replace: "ğŸš¨"

  - trigger: "fmoonÂ²"
    replace: "ğŸŒ"

  - trigger: "fireÂ²"
    replace: "ğŸ”¥"

  - trigger: "shinyÂ²"
    replace: "âœ¨"

  - trigger: "tadaÂ²"
    replace: "ğŸ‰"

  - trigger: "notesÂ²"
    replace: "ğŸ¶"

  - trigger: "phoneÂ²"
    replace: "â˜"

  - trigger: "titreÂ²"
    replace: "ğŸ“™"

  - trigger: "moneyÂ²"
    replace: "ğŸ’°"

  - trigger: "noÂ²"
    replace: "â›”"

  - trigger: "nuclearÂ²"
    replace: "â˜¢"

  - trigger: "biohazardÂ²"
    replace: "â˜£"

  - trigger: "lysÂ²"
    replace: "âšœ"

  - trigger: "checkÂ²"
    replace: "âœ”"

  - trigger: "usÂ²"
    replace: "ğŸ‡ºğŸ‡¸"

  - trigger: "mindblownÂ²"
    replace: "ğŸ¤¯"

  - trigger: "hotÂ²"
    replace: "ğŸ¥µ"

  - trigger: "partyÂ²"
    replace: "ğŸ¥³"

  - trigger: "sunglassesÂ²"
    replace: "ğŸ˜"

  - trigger: "starÂ²"
    replace: "ğŸŒ "

  - trigger: "deÂ²"
    replace: "ğŸ‡©ğŸ‡ª"

  - trigger: "omÂ²"
    replace: "ğŸ•‰"

  - trigger: "frÂ²"
    replace: "ğŸ‡«ğŸ‡·"

  - trigger: "gbÂ²"
    replace: "ğŸ‡¬ğŸ‡§"

  - trigger: "bizÂ²"
    replace: "(ã¥ï¿£ Â³ï¿£)ã¥ )"

  - trigger: "magieÂ²"
    replace: "(âˆ©ï½€-Â´)âŠƒâ”â˜†ï¾Ÿ.ï½¥ï½¡â˜†ï¾Ÿ.ï½¥ï½¡ï¾Ÿ)"

  - trigger: "tableÂ²"
    replace: "(â”›â—‰Ğ”â—‰)â”›å½¡â”»â”â”»)"



# Lutter contre la dyslexie dans les commandes :

  - trigger: "sud o "
    replace: "sudo "

  - trigger: "sduo "
    replace: "sudo "
    word: true
