# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  #   - trigger: "espansoÂ²"
  #  replace: "Kikoo lol !"

  # Signature
  - trigger: "dngÂ²"
    replace: "Bien cordialement,\n\n-- \nGuillaume Delanoy\nguillaume@delanoy.fr"

  - trigger: "dmgÂ²"
    replace: "Bien cordialement,\n\n-- \nGuillaume Delanoy\ngdelanoy@gmail.com"

    # Date
    #  - trigger: "dÂ²"
    # replace: "{{mydate}}"
    # vars:
    #   - name: mydate
    #    type: date
    #    params:
    #      format: "%d/%m/%Y"

  - trigger: "dateÂ²"
    replace: "{{madate}}"
    vars:
      - name: madate
        type: date
        params:
          format: "%A %d %B %Y"

  # Heure
  - trigger: "hmÂ²"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%Hh %M"

  # Shell commands
#  - trigger: ":shell"
#    replace: "{{output}}"
#    vars:
#      - name: output
#        type: shell
#        params:
#          cmd: "echo Hello from your shell"

# Remplacer des caractÃ¨res par d'autres :

  - trigger: "szÂ²"
    replace: "ÃŸ"

  - trigger: "cÂ²"
    replace: "Â© "

  - trigger: "crÂ²"
    replace: "Â® "

  - trigger: "1/2"
    replace: "Â½ "
    word: true

  - trigger: "1/4"
    replace: "Â¼ "
    word: true

  - trigger: "3/4"
    replace: "Â¾ "
    word: true

  - trigger: "Ã§Â²"
    replace: "Ã‡"

  - trigger: "Ã©Â²"
    replace: "Ã‰"

  - trigger: "Ã¨Â²"
    replace: "Ãˆ"

  - trigger: "Ã¹Â²"
    replace: "Ã™"

  - trigger: "Ã Â²"
    replace: "Ã€"

  - trigger: "aeÂ²"
    replace: "Ã¦"

  - trigger: "oeÂ²"
    replace: "Å“"

# Remplacements personnalisÃ©s : 

  - trigger: "aaÂ²"
    replace: "AurÃ©lie-Anne "
    word: true

  - trigger: "adgÂ²"
    replace: "16 / 6, square Jean Monnet - 59120 Loos "
    word: true

  - trigger: "ajdÂ²"
    replace: "aujourd'hui "
    word: true

  - trigger: "bisouÂ²"
    replace: "(ã¥ï¿£ Â³ï¿£)ã¥ "
    word: true

  - trigger: "bjrÂ²"
    replace: "bonjour "
    word: true

  - trigger: "dÂ²"
    replace: "Delanoy "
    word: true

  - trigger: "enlumÂ²"
    replace: "(((Â¯`Â·._.Â·(Â¯`Â·._.Â· Text Â·._.Â·Â´Â¯)Â·._.Â·Â´Â¯))) "
    word: true

  - trigger: "gÂ²"
    replace: "Guillaume "
    word: true

  - trigger: "gdÂ²"
    replace: "Guillaume Delanoy "
    word: true

  - trigger: "gdmÂ²"
    replace: "guillaume@delanoy.fr "
    word: true

  - trigger: "geÂ²"
    replace: "Â¯\\\_(ãƒ„)_/Â¯ "
    word: true

  - trigger: "ggmÂ²"
    replace: "gdelanoy@gmail.com "
    word: true

  - trigger: "magieÂ²"
    replace: "(âˆ©ï½€-Â´)âŠƒâ”â˜†ï¾Ÿ.ï½¥ï½¡â˜†ï¾Ÿ.ï½¥ï½¡ï¾Ÿ) "
    word: true

  - trigger: "mehÂ²"
    replace: "â•­âˆ©â•®ï¼ˆï¸¶ï¸¿ï¸¶ï¼‰â•­âˆ©â•® "
    word: true

  - trigger: "rÂ²"
    replace: "rÃ©pondre Ã  "
    word: true

  - trigger: "tableÂ²"
    replace: "(â•¯Â°â–¡Â°ï¼‰â•¯ï¸µ â”»â”â”») "
    word: true

  - trigger: "zikÂ²"
    replace: "Â¸Â¸â™¬Â·Â¯Â·â™©Â¸Â¸â™ªÂ·Â¯Â·â™«Â¸Â¸Happy Birthday !Â¸Â¸â™¬Â·Â¯Â·â™©Â¸Â¸â™ªÂ·Â¯Â·â™«Â¸Â¸ "
    word: true

# Des emojis Ã  portÃ©e de clavier :

  - trigger: ";)Â²"
    replace: "ğŸ˜‰ "

  - trigger: ":/Â²"
    replace: "ğŸ˜• "

  - trigger: ":)Â²"
    replace: "ğŸ˜ƒ "

  - trigger: "alienÂ²"
    replace: "ğŸ‘½ "

  - trigger: "angelÂ²"
    replace: "ğŸ˜‡ "

  - trigger: "apesÂ²"
    replace: "ğŸ™ˆ ğŸ™‰ ğŸ™Š "

  - trigger: "arbreÂ²"
    replace: "ğŸŒ³ "

  - trigger: "armÂ²"
    replace: "ğŸ’ª "

  - trigger: "beerÂ²"
    replace: "ğŸ» "

  - trigger: "biohazardÂ²"
    replace: "â˜£ "

  - trigger: "bizÂ²"
    replace: "ğŸ˜˜ "

  - trigger: "boomÂ²"
    replace: "ğŸ’¥ "

  - trigger: "brainÂ²"
    replace: "ğŸ§  "

  - trigger: "bwaÂ²"
    replace: "ğŸ¤ª "

  - trigger: "catÂ²"
    replace: "ğŸˆ "

  - trigger: "champÂ²"
    replace: "ğŸ¾ "

  - trigger: "checkÂ²"
    replace: "âœ” "

  - trigger: "clapÂ²"
    replace: "ğŸ‘ "

  - trigger: "clownÂ²"
    replace: "ğŸ¤¡ "

  - trigger: "coldÂ²"
    replace: "ğŸ¥¶  "

  - trigger: "cultureÂ²"
    replace: "ğŸ§ "

  - trigger: "deÂ²"
    replace: "ğŸ‡©ğŸ‡ª "

  - trigger: "devilÂ²"
    replace: "ğŸ˜ˆ "

  - trigger: "dizzyÂ²"
    replace: "ğŸ¥´  "

  - trigger: "downÂ²"
    replace: "ğŸ‘‡ "

  - trigger: "eyesÂ²"
    replace: "ğŸ‘€ "

  - trigger: "fearÂ²"
    replace: "ğŸ˜± "

  - trigger: "fireÂ²"
    replace: "ğŸ”¥ "

  - trigger: "fistÂ²"
    replace: "âœŠ "

  - trigger: "fmoonÂ²"
    replace: "ğŸŒ "

  - trigger: "frÂ²"
    replace: "ğŸ‡«ğŸ‡· "

  - trigger: "friteÂ²"
    replace: "ğŸŸ "

  - trigger: "fuckÂ²"
    replace: "ğŸ–• "

  - trigger: "fuseeÂ²"
    replace: "ğŸš€ "

  - trigger: "gbÂ²"
    replace: "ğŸ‡¬ğŸ‡§ "

  - trigger: "gyroÂ²"
    replace: "ğŸš¨ "

  - trigger: "heartÂ²"
    replace: "ğŸ’– "

  - trigger: "heyesÂ²"
    replace: "ğŸ˜ "

  - trigger: "hotÂ²"
    replace: "ğŸ¥µ  "

  - trigger: "hugÂ²"
    replace: "ğŸ¤— "

  - trigger: "kissÂ²"
    replace: "ğŸ’‹ "

  - trigger: "leftÂ²"
    replace: "ğŸ‘ˆ "

  - trigger: "lolÂ²"
    replace: "ğŸ˜„ "

  - trigger: "lysÂ²"
    replace: "âšœ "

  - trigger: "maskÂ²"
    replace: "ğŸ˜· "

  - trigger: "metalÂ²"
    replace: "ğŸ¤˜ "

  - trigger: "mindblownÂ²"
    replace: "ğŸ¤¯ "

  - trigger: "moneyÂ²"
    replace: "ğŸ’° "

  - trigger: "nerdÂ²"
    replace: "ğŸ¤“ "

  - trigger: "noÂ²"
    replace: "â›” "

  - trigger: "notesÂ²"
    replace: "ğŸ¶ "

  - trigger: "nuclearÂ²"
    replace: "â˜¢ "

  - trigger: "okÂ²"
    replace: "ğŸ‘Œ "

  - trigger: "omÂ²"
    replace: "ğŸ•‰ "

  - trigger: "partyÂ²"
    replace: "ğŸ¥³  "

  - trigger: "partyÂ²"
    replace: "ğŸ¥³  "

  - trigger: "pastaÂ²"
    replace: "ğŸ "

  - trigger: "peaceÂ²"
    replace: "â˜® "

  - trigger: "phoneÂ²"
    replace: "â˜ "

  - trigger: "pigÂ²"
    replace: "ğŸ½ "

  - trigger: "poopÂ²"
    replace: "ğŸ’© "

  - trigger: "popcornÂ²"
    replace: "ğŸ¿ "

  - trigger: "prayÂ²"
    replace: "ğŸ™ "

  - trigger: "rageÂ²"
    replace: "ğŸ¤¬ "

  - trigger: "rajaÂ²"
    replace: "ğŸ§˜ "

  - trigger: "rightÂ²"
    replace: "ğŸ‘‰ "

  - trigger: "roflÂ²"
    replace: "ğŸ¤£ "

  - trigger: "roseÂ²"
    replace: "ğŸŒ¹ "

  - trigger: "santaÂ²"
    replace: "ğŸ… "

  - trigger: "shinyÂ²"
    replace: "âœ¨ "

  - trigger: "skullÂ²"
    replace: "â˜  "

  - trigger: "smirkÂ²"
    replace: "ğŸ˜ "

  - trigger: "sobÂ²"
    replace: "ğŸ˜­ "

  - trigger: "starÂ²"
    replace: "ğŸŒ  "

  - trigger: "sunglassesÂ²"
    replace: "ğŸ˜ "

  - trigger: "sushiÂ²"
    replace: "ğŸ£ "

  - trigger: "swagÂ²"
    replace: "ğŸ˜… "

  - trigger: "tadaÂ²"
    replace: "ğŸ‰ "

  - trigger: "thinkÂ²"
    replace: "ğŸ¤” "

  - trigger: "titreÂ²"
    replace: "ğŸ“™ "

  - trigger: "trekÂ²"
    replace: "ğŸ–– "

  - trigger: "unicornÂ²"
    replace: "ğŸ¦„ "

  - trigger: "upÂ² "
    replace: "ğŸ‘† "

  - trigger: "usÂ²"
    replace: "ğŸ‡ºğŸ‡¸ "

  - trigger: "vomitÂ²"
    replace: "ğŸ¤® "

  - trigger: "waveÂ²"
    replace: "ğŸ‘‹ "

  - trigger: "winkÂ²"
    replace: "ğŸ˜‰ "

  - trigger: "worldÂ²"
    replace: "ğŸŒ "

  - trigger: "wutÂ²"
    replace: "ğŸ˜³ "

  - trigger: "(y)"
    replace: "ğŸ‘ "

  - trigger: "yumÂ²"
    replace: "ğŸ˜‹ "

  - trigger: "zombieÂ²"
    replace: "ğŸ§Ÿ "

  - trigger: "zzzÂ²"
    replace: "ğŸ’¤ "

# Les lignes qui vont bien pour en rajouter encore :
#
#  - trigger: "Â²"
#    replace: ""
#

# Lutter contre la dyslexie dans les commandes :

  - trigger: "sud o"
    replace: "sudo "

  - trigger: "sduo"
    replace: "sudo "

  - trigger: "ssytemctl"
    replace: "systemctl "
